modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/armored_elytra/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "armored_elytra"
version = "${version}"
displayName = "Armored Elytra"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.armored_elytra]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.armored_elytra]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
